# Generated by Django 2.2.16 on 2023-03-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230322_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date', 'id'), 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
