SIGNUP_URL_NAME = 'users:signup'
# Use settings.LOGIN_URL
# LOGIN_URL_NAME = 'users:login'
LOGOUT_URL_NAME = 'users:logout'
PASSWORD_CHANGE_URL_NAME = 'users:password_change'
PASSWORD_CHANGE_DONE_URL_NAME = 'users:password_change_done'
PASSWORD_RESET_URL_NAME = 'users:password_reset'
PASSWORD_RESET_DONE_URL_NAME = 'users:password_reset_done'
PASSWORD_RESET_COMPLETE_URL_NAME = 'users:password_reset_complete'
PASSWORD_RESET_CONFIRM_URL_NAME = 'users:password_reset_confirm'

SIGNUP_TEMPLATE = 'users/signup.html'
LOGIN_TEMPLATE = 'users/login.html'
LOGOUT_TEMPLATE = 'users/logged_out.html'
PASSWORD_CHANGE_TEMPLATE = 'users/password_change_form.html'
PASSWORD_CHANGE_DONE_TEMPLATE = 'users/password_change_done.html'
PASSWORD_RESET_TEMPLATE = 'users/password_reset_form.html'
PASSWORD_RESET_DONE_TEMPLATE = 'users/password_reset_done.html'
PASSWORD_RESET_COMPLETE_TEMPLATE = 'users/password_reset_complete.html'
PASSWORD_RESET_CONFIRM_TEMPLATE = 'users/password_reset_confirm.html'
