INDEX_URL_NAME = 'posts:index'
FOLLOW_URL_NAME = 'posts:follow_index'
GROUP_LIST_URL_NAME = 'posts:group_list'
PROFILE_URL_NAME = 'posts:profile'
PROFILE_FOLLOW_URL_NAME = 'posts:profile_follow'
PROFILE_UNFOLLOW_URL_NAME = 'posts:profile_unfollow'
POST_DETAIL_URL_NAME = 'posts:post_detail'
ADD_COMMENT_URL_NAME = 'posts:add_comment'
POST_CREATE_URL_NAME = 'posts:post_create'
POST_EDIT_URL_NAME = 'posts:post_edit'

INDEX_TEMPLATE = 'posts/index.html'
FOLLOW_TEMPLATE = 'posts/follow.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
POST_CREATE_TEMPLATE = 'posts/create_post.html'
# POST_EDIT_TEMPLATE = 'posts/create_post.html'
